### ISSUE TITLE
Transparrent background?

### ISSUE THREAD

**Issue by cprn** [elock37/wal_vtop#3]
Is there a way (a setting maybe?) to generate themes that don't make the process list background opaque?
![image](https://user-images.githubusercontent.com/6132708/78509597-6a8ee600-778f-11ea-873a-4d21b3d64ba0.png)

It's transparent in default theme:
![image](https://user-images.githubusercontent.com/6132708/78509615-8befd200-778f-11ea-94cc-71d8fac2c5e9.png)

**Comment by 3vanlock** [comment]
It seems like a good idea to align with vtop.

Change is likely to [the color scheme JSON](https://github.com/3vanlock/wal_vtop/blob/48ce700cf11e10b27051774e9391d8724e5b97bd/wal_vtop.py#L67)

**Comment by cprn** [comment]
Yup, commenting this line fixes the issue.

**Comment by cprn** [comment]
Sorry for bothering but I can't find a commit. Did you just close it or fixed it?

**Comment by 3vanlock** [comment]
Sorry, thought I [linked the commit](https://github.com/3vanlock/wal_vtop/commit/7c13792a14deed08882e59fe3b708ba00fa5aa5d). Didn't bother with a PR
